// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DrawData = { "type": "drySpectrum", "data": Array<[number, number]> } | { "type": "wetSpectrum", "data": Array<[number, number]> };
