// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DrawData = { "type": "spectrum", "data": { dry: Array<[number, number]>, wet: Array<[number, number]>, frequency_response: Array<[number, number]>, } };
