// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DrawData = { "drawType": "spectrum", "drawData": { dry: Array<number>, wet: Array<number>, } } | { "drawType": "frequencyResponse", "drawData": Array<[number, number]> };
